#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon -S -b -x $DAEMON
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon -K -n $DAEMON_NAME
        ;;
    restart)
        echo "Restarting $DAEMON_NAME..."
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0