#!/bin/sh


case "$1" in
    start)
        echo "Loading aesdchar kernel module"
        /etc/init.d/aesdchar_load
        ;;
    stop)
        echo "Unloading aesdchar kernel module"
        /etc/init.d/aesdchar_unload
        ;;
    restart)
        echo "Reloading aesdchar kernel module"
        /etc/init.d/aesdchar_unload
        /etc/init.d/aesdchar_load
        ;;
    *)
        echo "Usage $0 {start | stop | restart}"
    exit 1
esac